### ISSUE TITLE
`FactorialOf` defined multiple times

### ISSUE THREAD

**Issue by Y-Less** [iPollo/PawnAlgorithms#5]
In three different files (at least) making them mutually exclusive.  They should just include `FactorialOf.pwn`.

**Comment by iPollo** [comment]
Yes, if it was a single pack, but assuming you access specifically one of the functions, which use FactorialOf.pwn, I could just indicate with a redirect link or place the function, I chose the last choice.

Because the idea is that, primarily, the files work separately and are "self-sufficient".
I'm not sure if that's what you mean.

**Comment by Y-Less** [comment]
But that way you can never use two of them.
